name: Test and coverage

on:
  push:
    paths:
    - 'api/**_test.go'
    branches: [ main ]
  pull_request:
    paths:
    - 'api/**_test.go'
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v2
        with:
          go-version: '1.19'

      - name: Save coverage report of CIVO
        working-directory: api/civo
        run: |
          go test -race -coverprofile=../../coverage-civo.out -v ./...
          cd ..
          echo "# Coverage Report (CIVO API)
          " > coverage-civo.md
          go tool cover -func=coverage-civo.out >> coverage-civo.md

      - name: save coverage report of LOCAL
        working-directory: api/local
        run: |
          go test -race -coverprofile=../../coverage-local.out -v ./...
          cd ..
          echo "# Coverage Report (LOCAL API)
          " > coverage-local.md
          go tool cover -func=coverage-local.out >> coverage-local.md

      - name: save coverage report of UTILS
        working-directory: api/utils
        run: |
          go test -race -coverprofile=../../coverage-utils.out -v ./...
          cd ..
          echo "# Coverage Report (UTILS API)
          " > coverage-utils.md
          go tool cover -func=coverage-utils.out >> coverage-utils.md
   

      - name: PR comment for code coverage for CIVO
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: coverage-civo.md

      - name: PR comment for code coverage for LOCAL
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: coverage-local.md

      - name: PR comment for code coverage for UTILS
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: coverage-utils.md
