name: Testing API
on:
  push:
    paths:
    - 'api/**'
    branches: [ main ]
  pull_request:
    paths:
    - 'api/**'
    branches: [ main ]

jobs:
  API_on_Linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.0' # The Go version to download (if necessary) and use.
      - name: Unit-Testing
        run: |
           cd api
           chmod +x test-api.sh
           ./test-api.sh

  API_on_Macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.0' # The Go version to download (if necessary) and use.
      - name: Unit-Testing
        run: |
           cd api
           chmod +x test-api.sh
           ./test-api.sh

  API_on_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.19.0' # The Go version to download (if necessary) and use.
      - name: Unit-Testing
        run: |
           cd api
           .\test-api.ps1
