name: Testing Build process
on:
  push:
    paths:
    - 'internal/**'
    - 'pkg/**'
    - 'cmd/cli/**'
    - 'go.mod'
    - 'go.sum'
    branches: [ main ]
  pull_request:
    paths:
    - 'internal/**'
    - 'pkg/**'
    - 'cmd/cli/**'
    - 'go.mod'
    - 'go.sum'
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Build and install the latest version
        run: |
          make install_linux
          ksctl -h

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.
      - run: go version
      # TODO: add support to check for the M1 chip as well
      - name: Build and install the latest version on intel chip
        run: |
          make install_macos_intel
          ksctl -h

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20' # The Go version to download (if necessary) and use.
      - run: go version
      - name: Build and install the latest version
        run: |
          cd .\scripts
          .\builder.ps1
          cd C:\Users\runneradmin\AppData\Local\ksctl
          .\ksctl.exe -h
