name: Regression Test Local
on:
  push:
    paths:
    - 'internal/cloudproviders/local/**'
    - 'internal/storage/**'
    - 'pkg/logger/**'
    - 'pkg/utils/**'
    - 'go.mod'
    - 'go.sum'
    branches: [ main ]
  pull_request:
    types: [ labeled, opened, synchronize, reopened, edited ]
    paths:
    - 'internal/cloudproviders/local/**'
    - 'internal/storage/**'
    - 'pkg/logger/**'
    - 'pkg/utils/**'
    - 'go.mod'
    - 'go.sum'

jobs:
  unit-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}
    if: ${{ github.event.label.name != 'pr/lgtm' }}

    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Testing
        if: ${{ matrix.os != 'windows-latest' }}
        working-directory: scripts
        run: |
          chmod u+x test-local.sh
          ./test-local.sh

      - name: Testing
        if: ${{ matrix.os == 'windows-latest' }}
        working-directory: scripts
        run: .\test-local.ps1

  mock-integration-test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.os }}

    if: ${{ github.event.label.name == 'pr/lgtm' }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: integration testing
        working-directory: test
        run: go test -bench=BenchmarkLocalTestingManaged -benchtime=1x -cover -v

