name: Unit-Testing API
on:
  push:
    paths:
      - 'internal/**'
      - 'pkg/**'
    branches: [ main ]
  pull_request:
    paths:
      - 'internal/**'
      - 'pkg/**'
    branches: [ main ]

jobs:
  API_on_Linux:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes in specific folder
        id: changes
        uses: dorny/paths-filter@v2
        with:
          filters: |
            civo:
              - 'internal/cloudproviders/civo/**'
              - 'internal/storagelogger/**'
              - 'pkg/utils/**'
              - 'pkg/logger/**'
            
            azure:
              - 'internal/cloudproviders/azure/**'
              - 'internal/storagelogger/**'
              - 'pkg/utils/**'
              - 'pkg/logger/**'
            
            local:
              - 'internal/cloudproviders/local/**'
              - 'internal/storagelogger/**'
              - 'pkg/logger/**'
              - 'pkg/utils/**'
            
            k3s:
              - 'internal/k8sdistros/k3s/**'
              - 'internal/storagelogger/**'
              - 'pkg/logger/**'
              - 'pkg/utils/**'
            
            logger:
              - 'pkg/logger/**'
            
            utils:
              - 'pkg/utils/**'

      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.0' # The Go version to download (if necessary) and use.
      - name: Unit-Testing-civo
        if: steps.changes.outputs.civo == 'true'
        run: |
          cd scripts
          chmod u+x test-civo.sh
          ./test-civo.sh

      - name: Unit-Testing-azure
        if: steps.changes.outputs.azure == 'true'
        run: |
          cd scripts
          chmod u+x test-azure.sh
          ./test-azure.sh

      - name: Unit-Testing-local
        if: steps.changes.outputs.local == 'true'
        run: |
          cd scripts
          chmod u+x test-local.sh
          ./test-local.sh

      - name: Unit-Testing-k3s
        if: steps.changes.outputs.k3s == 'true'
        run: |
          cd scripts
          chmod u+x test-k3s.sh
          ./test-k3s.sh

      - name: Unit-Testing-logger
        if: steps.changes.outputs.logger == 'true'
        run: |
          cd scripts
          chmod u+x test-logger.sh
          ./test-logger.sh

      - name: Unit-Testing-utils
        if: steps.changes.outputs.utils == 'true'
        run: |
          cd scripts
          chmod u+x test-utils.sh
          ./test-utils.sh

  API_on_Macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.0' # The Go version to download (if necessary) and use.
      - name: Unit-Testing-civo
        if: steps.changes.outputs.civo == 'true'
        run: |
          cd scripts
          chmod u+x test-civo.sh
          ./test-civo.sh

      - name: Unit-Testing-azure
        if: steps.changes.outputs.azure == 'true'
        run: |
          cd scripts
          chmod u+x test-azure.sh
          ./test-azure.sh

      - name: Unit-Testing-local
        if: steps.changes.outputs.local == 'true'
        run: |
          cd scripts
          chmod u+x test-local.sh
          ./test-local.sh

      - name: Unit-Testing-k3s
        if: steps.changes.outputs.k3s == 'true'
        run: |
          cd scripts
          chmod u+x test-k3s.sh
          ./test-k3s.sh

      - name: Unit-Testing-logger
        if: steps.changes.outputs.logger == 'true'
        run: |
          cd scripts
          chmod u+x test-logger.sh
          ./test-logger.sh

      - name: Unit-Testing-utils
        if: steps.changes.outputs.utils == 'true'
        run: |
          cd scripts
          chmod u+x test-utils.sh
          ./test-utils.sh

  API_on_Windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.20.0' # The Go version to download (if necessary) and use.
      - name: Unit-Testing-civo
        if: steps.changes.outputs.civo == 'true'
        run: |
          cd scripts
          .\test-civo.ps1

      - name: Unit-Testing-azure
        if: steps.changes.outputs.azure == 'true'
        run: |
          cd scripts
          .\test-azure.ps1

      - name: Unit-Testing-local
        if: steps.changes.outputs.local == 'true'
        run: |
          cd scripts
          .\test-local.ps1

      - name: Unit-Testing-k3s
        if: steps.changes.outputs.k3s == 'true'
        run: |
          cd scripts
          .\test-k3s.ps1

      - name: Unit-Testing-logger
        if: steps.changes.outputs.logger == 'true'
        run: |
          cd scripts
          .\test-logger.ps1

      - name: Unit-Testing-utils
        if: steps.changes.outputs.utils == 'true'
        run: |
          cd scripts
          .\test-utils.ps1
