name: Unit-Testing API
on:
  push:
    paths:
    - 'internal/cloudproviders/local/**'
    - 'internal/storage/**'
    - 'pkg/logger/**'
    - 'pkg/utils/**'
    - 'go.mod'
    - 'go.sum'
    branches: [ main ]
  pull_request:
    paths:
    - 'internal/cloudproviders/local/**'
    - 'internal/storage/**'
    - 'pkg/logger/**'
    - 'pkg/utils/**'
    - 'go.mod'
    - 'go.sum'
    branches: [ main ]

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Unit Test
        run: |
          cd scripts
          chmod u+x test-local.sh
          ./test-local.sh

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Unit Test
        run: |
          cd scripts
          .\test-local.ps1

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.0

      - name: Unit Test
        run: |
          cd scripts
          chmod u+x test-local.sh
          ./test-local.sh